### PR TITLE
remove requirement for matching iss claim in Referenced Token and Sta…

### LINKED ISSUE #108: do we mandate the issuer of Referenced Token is the same entity issuing the Status List?

### LINKED ISSUE #159: Remove requirement on matching iss values
To allow Status List Issuer being different from Issuer and using iss values, we should remove this constraint

### PR DESCRIPTION
**Pull request by paulbastian**
Closes #159 
Closes #108

### CODE REVIEW

**Review by c2bo — APPROVED** [review]

**Comment by c2bo** [comment]
We should adjust our examples to remove iss then - want me to push to this PR before we merge, or create another PR?

**Comment by paulbastian** [comment]
its still present in Referenced Token in JWT format. Shall we remove it?

**Comment by paulbastian** [comment]
Otherwise approved, as I can't review my own PR apparently

**Comment by paulbastian** [comment]
@tplooker please review

**Pull request merged**
